// The pad voices. No DCL imports, so the tuning is unit-testable on its own.
//
// A memory game is only half a visual game: the reason Simon works is that the
// sequence is a tune, and a tune is far easier to hold in your head than four
// coloured flashes. Eight pads therefore have eight pitches, and repeating a
// chain means repeating a melody.
//
// One clip does all of it. AudioSource exposes a `pitch` multiplier, so
// sounds/pad.wav (generated by scripts/make-sound.mjs) is played at these ratios
// rather than shipping eight recordings.

import { EMOTES } from './game.ts'

/** The one clip in the scene, as named in the deploy manifest. */
export const CLIP = 'sounds/pad.wav'

/**
 * Semitones above the recorded pitch, one per pad, low to high.
 *
 * A major pentatonic run over an octave and a third: every pad is a step the ear
 * can name, and no two are a semitone apart, so a chain never sounds like a
 * mistake. Order matches the pads' clockwise order on the stage.
 */
const SEMITONES = [0, 2, 4, 7, 9, 12, 14, 16]

/** Frequency ratio for a number of equal-tempered semitones. */
export function ratio(semitones: number): number {
  return 2 ** (semitones / 12)
}

/**
 * Playback rate per pad. Derived from EMOTES so a ninth pad cannot silently
 * arrive without a voice - the test holds these two lengths together.
 */
export const PAD_PITCH: number[] = EMOTES.map((_, i) => ratio(SEMITONES[i] ?? 0))

/**
 * A miss, an octave and a half below the lowest pad.
 *
 * Deliberately the same clip: a low, slow version of the pad sound reads as "the
 * chain fell over" rather than as a different game announcing an error.
 */
export const MISS_PITCH = ratio(-18)
